In [76]:
from sklearn import metrics,preprocessing
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split


keepdims = True
correct = 0
modacc = .69
att = 0
lab = preprocessing.LabelEncoder()
# ctrl+f your path leading to data
bundle_data = pd.read_csv(r'G:\ML Class\BDP\BDPdataClean.csv')



training_data, testing_data = train_test_split(bundle_data, test_size=0.02, random_state=33)


#get parameter and split
X_test = testing_data[['AWG20','AWG22','AWG24']]
y_test = testing_data[['Diameter']]

X_train = training_data[['AWG20','AWG22','AWG24']]
y_train = training_data[['Diameter']]


#Scale paremeters
scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
#X_train = [x for x in X_train if str(x) != 'nan']
scaler.fit(X_test)
X_test = scaler.transform(X_test)

#run KNN
knn = KNeighborsClassifier(n_neighbors=5)

knn.fit(X_train, y_train)

y_pred = knn.predict(X_test)



print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

ypred=y_pred.tolist()
print(ypred)
print(y_test)



Accuracy: 0.0
[7, 7]
    Diameter
57         6
26         6
[[-1.  1.  0.]
 [ 1. -1.  0.]]


C:\Users\tgrim\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\neighbors\_classification.py:207: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


In [95]:
from sklearn.ensemble import RandomForestClassifier


clf = RandomForestClassifier(n_jobs=2, random_state=10)



clf.fit(X_train,y_train)
print(y_test)
clf.predict(X_test)






    Diameter
40        11
42         6
2          7
49         5
51         5
26         6
34         8
36        15
41         8
39         7


C:\Users\tgrim\AppData\Local\Temp\ipykernel_22676\1406006021.py:8: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  clf.fit(X_train,y_train)


array([11,  5,  6, 10, 10, 10,  7, 15,  5,  5], dtype=int64)

: 